import { useState } from "react";
import { useParams, Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { ChevronLeft, ChevronRight, RotateCcw } from "lucide-react";
import Navbar from "@/components/Navbar";

// Sample flashcard data
const flashcardData: Record<string, any[]> = {
  "security-plus": [
    { question: "What is CIA in cybersecurity?", answer: "Confidentiality, Integrity, and Availability - the three pillars of information security." },
    { question: "What is the difference between symmetric and asymmetric encryption?", answer: "Symmetric uses one key for both encryption and decryption, while asymmetric uses a public/private key pair." },
    { question: "What is multi-factor authentication (MFA)?", answer: "A security system that requires multiple methods of authentication from independent categories to verify user identity." },
    { question: "What is a firewall?", answer: "A network security system that monitors and controls incoming and outgoing network traffic based on predetermined security rules." },
    { question: "What is social engineering?", answer: "Manipulation techniques that exploit human psychology to trick users into making security mistakes or giving away sensitive information." }
  ],
  "network-plus": [
    { question: "What is the OSI model?", answer: "A 7-layer conceptual framework that describes how data communications occur between systems: Physical, Data Link, Network, Transport, Session, Presentation, Application." },
    { question: "What is the difference between TCP and UDP?", answer: "TCP is connection-oriented and reliable, while UDP is connectionless and faster but less reliable." },
    { question: "What is a subnet mask?", answer: "A 32-bit number that divides an IP address into network and host portions." },
    { question: "What is DHCP?", answer: "Dynamic Host Configuration Protocol - automatically assigns IP addresses to devices on a network." },
    { question: "What is DNS?", answer: "Domain Name System - translates human-readable domain names to IP addresses." }
  ],
  "cysa-plus": [
    { question: "What is threat intelligence?", answer: "Evidence-based knowledge about existing or emerging threats that can be used to inform decisions about security." },
    { question: "What is a SIEM?", answer: "Security Information and Event Management - provides real-time analysis of security alerts generated by applications and network hardware." },
    { question: "What is incident response?", answer: "A structured approach to handling security breaches or attacks, including preparation, detection, containment, eradication, and recovery." },
    { question: "What is vulnerability assessment?", answer: "The process of identifying, quantifying, and prioritizing vulnerabilities in a system." },
    { question: "What is penetration testing?", answer: "Simulated cyber attack against a system to check for exploitable vulnerabilities." }
  ]
};

const Flashcards = () => {
  const { certId } = useParams();
  const [currentIndex, setCurrentIndex] = useState(0);
  const [isFlipped, setIsFlipped] = useState(false);
  
  const cards = flashcardData[certId || "security-plus"] || flashcardData["security-plus"];
  const currentCard = cards[currentIndex];
  const progress = ((currentIndex + 1) / cards.length) * 100;

  const handleNext = () => {
    if (currentIndex < cards.length - 1) {
      setCurrentIndex(currentIndex + 1);
      setIsFlipped(false);
    }
  };

  const handlePrevious = () => {
    if (currentIndex > 0) {
      setCurrentIndex(currentIndex - 1);
      setIsFlipped(false);
    }
  };

  const handleReset = () => {
    setCurrentIndex(0);
    setIsFlipped(false);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-background to-secondary">
      <Navbar />
      
      <div className="container mx-auto px-4 py-12">
        <div className="max-w-3xl mx-auto">
          <div className="mb-8">
            <Link to="/certifications">
              <Button variant="ghost" className="mb-4">
                ← Back to Certifications
              </Button>
            </Link>
            <h1 className="text-4xl font-bold mb-2">Flashcards</h1>
            <p className="text-muted-foreground">Click the card to flip and reveal the answer</p>
          </div>

          <div className="mb-6">
            <div className="flex items-center justify-between mb-2">
              <span className="text-sm font-medium">
                Card {currentIndex + 1} of {cards.length}
              </span>
              <Button variant="outline" size="sm" onClick={handleReset}>
                <RotateCcw className="h-4 w-4 mr-2" />
                Reset
              </Button>
            </div>
            <Progress value={progress} className="h-2" />
          </div>

          <Card 
            className="relative h-96 cursor-pointer perspective-1000 mb-8"
            onClick={() => setIsFlipped(!isFlipped)}
          >
            <div 
              className={`absolute inset-0 transition-all duration-500 transform-style-3d ${
                isFlipped ? 'rotate-y-180' : ''
              }`}
              style={{ transformStyle: 'preserve-3d' }}
            >
              {/* Front of card */}
              <div 
                className={`absolute inset-0 backface-hidden p-8 flex items-center justify-center text-center bg-gradient-to-br from-card to-card/50 rounded-lg border-2 ${
                  isFlipped ? 'invisible' : 'visible'
                }`}
                style={{ backfaceVisibility: 'hidden' }}
              >
                <div>
                  <div className="text-sm text-primary font-semibold mb-4">QUESTION</div>
                  <p className="text-2xl font-medium">{currentCard.question}</p>
                  <p className="text-sm text-muted-foreground mt-8">Click to reveal answer</p>
                </div>
              </div>
              
              {/* Back of card */}
              <div 
                className={`absolute inset-0 backface-hidden p-8 flex items-center justify-center text-center bg-gradient-to-br from-primary/10 to-accent/10 rounded-lg border-2 border-primary ${
                  isFlipped ? 'visible' : 'invisible'
                }`}
                style={{ 
                  backfaceVisibility: 'hidden',
                  transform: 'rotateY(180deg)'
                }}
              >
                <div>
                  <div className="text-sm text-primary font-semibold mb-4">ANSWER</div>
                  <p className="text-xl">{currentCard.answer}</p>
                  <p className="text-sm text-muted-foreground mt-8">Click to see question</p>
                </div>
              </div>
            </div>
          </Card>

          <div className="flex justify-between items-center">
            <Button 
              variant="outline" 
              onClick={handlePrevious}
              disabled={currentIndex === 0}
              size="lg"
            >
              <ChevronLeft className="h-5 w-5 mr-2" />
              Previous
            </Button>
            
            <Button 
              variant="outline" 
              onClick={handleNext}
              disabled={currentIndex === cards.length - 1}
              size="lg"
            >
              Next
              <ChevronRight className="h-5 w-5 ml-2" />
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Flashcards;
